name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build
        run: | 
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\" 
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\githus-actions-console-framework-4-6-2.sln /P:Configuration=Release
          cd \
          mkdir mactemp
          cd \mactemp
          copy $Env:GITHUB_WORKSPACE\githus-actions-console-framework-4-6-2\bin\release\*.exe
          .\7z.exe a *.exe githus-actions-console-framework-4-6-2.zip
          dir
          
          
          
          
